{% set version = "4.3.1" %}

package:
  name: visan
  version: {{ version }}

source:
  url: https://github.com/stcorp/visan/archive/refs/tags/{{ version }}.tar.gz
  sha256: 991b7b09f35fc253493d0d6b47e1722ca915da3d4c68824cea7962e9b56d13ed

build:
  number: 5
  osx_is_app: true  # [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

  host:
    - proj >=8.2
    - python
    - vtk >=9.1 osmesa*  # [linux]
    - vtk >=9.1         # [not linux]

  run:
    - coda
    - harp
    - numpy
    - proj >=8.2
    - python
    - vtk >=9.1
    - wxpython

test:
  imports:
    - visan.app
    - visan.plot.visanplot

app:
  entry: visan
  icon: logo.png
  summary: Visualization and Analysis application of the Atmospheric Toolbox

about:
  home: https://github.com/stcorp/visan
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: COPYING
  summary: Visualization and Analysis application of the Atmospheric Toolbox

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
