{% set version = "4.3" %}

package:
  name: visan
  version: {{ version }}

source:
  url: https://github.com/stcorp/visan/archive/refs/tags/{{ version }}.tar.gz
  sha256: a28e4c613371d6add6b45a790d0702db842e11cefc31e2260d7941d4eae3231e

build:
  number: 2
  osx_is_app: true  # [osx]

requirements:
  build:
    - sysroot_linux-64 2.17 [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

  host:
    - proj >=8.2
    - python
    - vtk >=9.1

  run:
    - coda
    - harp
    - numpy
    - proj >=8.2
    - python
    - vtk >=9.1
    - wxpython

test:
  imports:
    - visan.app
    - visan.plot.visanplot

app:
  entry: visan
  icon: logo.png
  summary: Visualization and Analysis application of the Atmospheric Toolbox

about:
  home: https://github.com/stcorp/visan
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: COPYING
  summary: Visualization and Analysis application of the Atmospheric Toolbox

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
